import type { Meta, StoryObj } from '@storybook/react'
import DocumentLibraryPlayground from './components/DocumentLibraryPlayground'

const meta: Meta<typeof DocumentLibraryPlayground> = {
  title: 'App',
  component: DocumentLibraryPlayground,
  argTypes: {
    documentSetName: {
      control: { type: 'text' },
    },
  },
}

export default meta

type Story = StoryObj<typeof DocumentLibraryPlayground>

export const Default: Story = {
  args: {
    graphToken: "eyJ0eXAiOiJKV1QiLCJub25jZSI6Il96LTRxTmlDOERPZzlRLXliMEc2M0lrRm5tQlo5aVBEMHN3MG94ZS1zR0EiLCJhbGciOiJSUzI1NiIsIng1dCI6Ilh0LW83aERicHVwQXotWlBtNkh4Q0ZXUzNjSSIsImtpZCI6Ilh0LW83aERicHVwQXotWlBtNkh4Q0ZXUzNjSSJ9.eyJhdWQiOiJodHRwczovL2dyYXBoLm1pY3Jvc29mdC5jb20iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8yZjI1OTFhMi0xY2YyLTQ2YWEtOTlkOC04OTQ2NzY1OTY1YzkvIiwiaWF0IjoxNzc4NTc1NDgzLCJuYmYiOjE3Nzg1NzU0ODMsImV4cCI6MTc3ODU4MDM3MiwiYWNjdCI6MCwiYWNyIjoiMSIsImFjcnMiOlsiYzEiXSwiYWlvIjoiQVVRQXUvOGNBQUFBMG04bittRk85YUptNHMrZW9lcDZwakU0S3ZUR3JESENIbzBQaTJhc0R3alJFZjRpMWVEalhVTFZJZXcxNTVQWWdqSVQwdytDYW00MWhkeVZjMmd5bFE9PSIsImFtciI6WyJwd2QiLCJyc2EiXSwiYXBwX2Rpc3BsYXluYW1lIjoiRzIgRG9jcyBSZXNvdXJjZSBVSSBOb25Qcm9kIiwiYXBwaWQiOiJiMTMwNTEzMS1lNzIyLTRhZGEtOTUwMy1jZGM2N2Y5NzMwNzAiLCJhcHBpZGFjciI6IjAiLCJkZXZpY2VpZCI6ImNhNmE5ZmE3LWJlN2UtNGM1MC04ODFhLTU5ZGI4MmJkMGNhYiIsImlkdHlwIjoidXNlciIsImlwYWRkciI6IjUyLjE1MS4yMjguMTE0IiwibmFtZSI6Ik11YmFzaGlyIEFsdGFmIiwib2lkIjoiZWY1OGMzZTEtMjEwMS00NzgyLWIzY2YtZDlhYWQ4MGMzZDFhIiwicGxhdGYiOiIzIiwicHVpZCI6IjEwMDMyMDA0RTFDNDZDM0EiLCJyaCI6IjEuQVdNQm9wRWxMX0ljcWthWjJJbEdkbGxseVFNQUFBQUFBQUFBd0FBQUFBQUFBQUFBQUtWakFRLiIsInNjcCI6IkRpcmVjdG9yeS5SZWFkLkFsbCBGaWxlcy5SZWFkIEZpbGVzLlJlYWQuQWxsIEZpbGVzLlJlYWRXcml0ZSBHcm91cC5SZWFkLkFsbCBTaXRlcy5SZWFkLkFsbCBTaXRlcy5SZWFkV3JpdGUuQWxsIFNpdGVzLlNlYXJjaC5BbGwgU2l0ZXMuU2VsZWN0ZWQgVGVybVN0b3JlLlJlYWRXcml0ZS5BbGwgVXNlci5SZWFkIFVzZXIuUmVhZFdyaXRlLkFsbCIsInNpZCI6IjAwNDEyZjlhLWZmNjUtNWZhOS0wMzA0LWFhYmYwNGMzMTI4NyIsInNpZ25pbl9zdGF0ZSI6WyJrbXNpIl0sInN1YiI6Ino2UHZEY1hLaXVPSWU4Y2J3N0VDd0pKTVhBMHlBb25zVUV2QWpvMEQ2cTgiLCJ0ZW5hbnRfcmVnaW9uX3Njb3BlIjoiTkEiLCJ0aWQiOiIyZjI1OTFhMi0xY2YyLTQ2YWEtOTlkOC04OTQ2NzY1OTY1YzkiLCJ1bmlxdWVfbmFtZSI6Im11YmFzaGlyLmFsdGFmQGdlbnN0YXJnZW5lc2lzLm9ubWljcm9zb2Z0LmNvbSIsInVwbiI6Im11YmFzaGlyLmFsdGFmQGdlbnN0YXJnZW5lc2lzLm9ubWljcm9zb2Z0LmNvbSIsInV0aSI6IktiaS01M0treGtLZlROd2JVR2FUQUEiLCJ2ZXIiOiIxLjAiLCJ3aWRzIjpbImI3OWZiZjRkLTNlZjktNDY4OS04MTQzLTc2YjE5NGU4NTUwOSJdLCJ4bXNfYWNkIjoxNzYxOTA0OTk0LCJ4bXNfYWN0X2ZjdCI6IjMgOSIsInhtc19mdGQiOiJINUVBWDVFM0M5MkRUQm96LVBTczdQaFN4Rml4cW4wZW5LNjFKNkhodjlNQmRYTmxZWE4wTFdSemJYTSIsInhtc19pZHJlbCI6IjI4IDEiLCJ4bXNfcGZ0ZXhwIjoxNzc4NjY2NzcyLCJ4bXNfc3ViX2ZjdCI6IjMgMjAiLCJ4bXNfdGNkdCI6MTc1MjU4NjEwOSwieG1zX3RudF9mY3QiOiIxOCAzIn0.bow8Fq2sImtO8-N1wSUP8_DJcGag4mov9LIKGiwxSGVdIEcspgbpVAhcfZnXZ0Rq1D_EVreoY_LZWbr8GDW5yDLFZm6hxLh-AifU5s6-as_BhO8bqH-tZbFVZ45OKBmAQ_3ZGWPVUHxpCULPmP9QhAHwDo6hq8wvdSZM3ru8Wj1iqqj3m0XNKNDiYnlPC8RBNFUyiZ5cxHhMQYvnuw_kL47b6FS-lsqMhTPpk6VfnHNdBCAMZaPtN1t3fB-hXklOPATuxzWDfHAg8wz51uqKLkcGxVXI2DjwKuJTHzmWIyPYsu_tLo80BesC54AGKhg1p6WHxv-IJQTQSzLdh3-9LQ",

    // siteUrl: "https://genre.sharepoint.com/sites/G2Applications-DEV/FormsLibrary",
    siteUrl: "https://genstargenesis.sharepoint.com/sites/Indexing-dev",

    // listName: "Documents",
    listName: "G2IndexingUnderwriting",

    documentSetName: "MubashirTest",
    // Upload now derives the authenticated user from token claims.

    columns: {
      "Title": "",
      "ContentType": ""
    },

    showActions: false,
    showBreadcrumb: true,
    showUploadControls: true
  }
}

