import type { Meta, StoryObj } from '@storybook/react'
import DocumentLibraryPlayground from './components/DocumentLibraryPlayground'

const meta: Meta<typeof DocumentLibraryPlayground> = {
  title: 'App',
  component: DocumentLibraryPlayground,
  argTypes: {
    documentSetName: {
      control: { type: 'text' },
    },
  },
}

export default meta

type Story = StoryObj<typeof DocumentLibraryPlayground>

export const Default: Story = {
  args: {
    graphToken: "eyJ0eXAiOiJKV1QiLCJub25jZSI6InkxOWI1WkNYYWgzcjVFaVF4RGRRZFR3SXNWZjhkZ3ZncTc5dHl6ejAxa0EiLCJhbGciOiJSUzI1NiIsIng1dCI6Ilh0LW83aERicHVwQXotWlBtNkh4Q0ZXUzNjSSIsImtpZCI6Ilh0LW83aERicHVwQXotWlBtNkh4Q0ZXUzNjSSJ9.eyJhdWQiOiJodHRwczovL2dyYXBoLm1pY3Jvc29mdC5jb20iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8yZjI1OTFhMi0xY2YyLTQ2YWEtOTlkOC04OTQ2NzY1OTY1YzkvIiwiaWF0IjoxNzc4NjUyMjQ0LCJuYmYiOjE3Nzg2NTIyNDQsImV4cCI6MTc3ODY1Nzc4OSwiYWNjdCI6MCwiYWNyIjoiMSIsImFjcnMiOlsiYzEiXSwiYWlvIjoiQVVRQXUvOGNBQUFBSzFORE1TYkQ1VnZkTGRkaStEN2NkNjNCbkpOZStBZkUwN2laT3BHSlpDcFJSQzBVa1VLMmRQa2tjZnVVU2VYYlRZM0JyN2s0RmtJY3pCVWk0MVdpd3c9PSIsImFtciI6WyJwd2QiLCJyc2EiXSwiYXBwX2Rpc3BsYXluYW1lIjoiRzIgRG9jcyBSZXNvdXJjZSBVSSBOb25Qcm9kIiwiYXBwaWQiOiJiMTMwNTEzMS1lNzIyLTRhZGEtOTUwMy1jZGM2N2Y5NzMwNzAiLCJhcHBpZGFjciI6IjAiLCJkZXZpY2VpZCI6ImNhNmE5ZmE3LWJlN2UtNGM1MC04ODFhLTU5ZGI4MmJkMGNhYiIsImlkdHlwIjoidXNlciIsImlwYWRkciI6IjUyLjE1MS4yMjguMTE0IiwibmFtZSI6Ik11YmFzaGlyIEFsdGFmIiwib2lkIjoiZWY1OGMzZTEtMjEwMS00NzgyLWIzY2YtZDlhYWQ4MGMzZDFhIiwicGxhdGYiOiIzIiwicHVpZCI6IjEwMDMyMDA0RTFDNDZDM0EiLCJyaCI6IjEuQVdNQm9wRWxMX0ljcWthWjJJbEdkbGxseVFNQUFBQUFBQUFBd0FBQUFBQUFBQUFBQUtWakFRLiIsInNjcCI6IkRpcmVjdG9yeS5SZWFkLkFsbCBGaWxlcy5SZWFkIEZpbGVzLlJlYWQuQWxsIEZpbGVzLlJlYWRXcml0ZSBHcm91cC5SZWFkLkFsbCBTaXRlcy5SZWFkLkFsbCBTaXRlcy5SZWFkV3JpdGUuQWxsIFNpdGVzLlNlYXJjaC5BbGwgU2l0ZXMuU2VsZWN0ZWQgVGVybVN0b3JlLlJlYWRXcml0ZS5BbGwgVXNlci5SZWFkIFVzZXIuUmVhZFdyaXRlLkFsbCIsInNpZCI6IjAwNDEyZjlhLWZmNjUtNWZhOS0wMzA0LWFhYmYwNGMzMTI4NyIsInNpZ25pbl9zdGF0ZSI6WyJrbXNpIl0sInN1YiI6Ino2UHZEY1hLaXVPSWU4Y2J3N0VDd0pKTVhBMHlBb25zVUV2QWpvMEQ2cTgiLCJ0ZW5hbnRfcmVnaW9uX3Njb3BlIjoiTkEiLCJ0aWQiOiIyZjI1OTFhMi0xY2YyLTQ2YWEtOTlkOC04OTQ2NzY1OTY1YzkiLCJ1bmlxdWVfbmFtZSI6Im11YmFzaGlyLmFsdGFmQGdlbnN0YXJnZW5lc2lzLm9ubWljcm9zb2Z0LmNvbSIsInVwbiI6Im11YmFzaGlyLmFsdGFmQGdlbnN0YXJnZW5lc2lzLm9ubWljcm9zb2Z0LmNvbSIsInV0aSI6IlM4WlhUdnlMVDBLcXRVMkRpWUUxQUEiLCJ2ZXIiOiIxLjAiLCJ3aWRzIjpbImI3OWZiZjRkLTNlZjktNDY4OS04MTQzLTc2YjE5NGU4NTUwOSJdLCJ4bXNfYWNkIjoxNzYxOTA0OTk0LCJ4bXNfYWN0X2ZjdCI6IjMgOSIsInhtc19mdGQiOiJBSEFwcGlFZ2JFaEdTWEZMcXpXTm5yN2prdFMySHd4cDhoT21QQUVFdk5jQmRYTmxZWE4wTFdSemJYTSIsInhtc19pZHJlbCI6IjMyIDEiLCJ4bXNfcGZ0ZXhwIjoxNzc4NzQ0MTg5LCJ4bXNfc3ViX2ZjdCI6IjMgNiIsInhtc190Y2R0IjoxNzUyNTg2MTA5LCJ4bXNfdG50X2ZjdCI6IjMgNCJ9.jQaFRQp1Vel_H8hB4Adc167KLtjOS861Zi5lCQ01UerR7BLsVdE7LTJJYi9Tlpx1hnXRqRRk6rdlXlhVTb4kdOMesbp1RG3mRwAc1Lph_-KuR4O3Nw0yE-JYCzIo4HdFRgwCz_-8DJ6Z7tyF43crHR67hWz65Esa_jZwN-EEk3R_uPfhsdbPgwkjh7dbV4gN3CPadQxa3COhyXcz80BHmLc8CD7i-322Lw88MPaNMSbg0LZ4fnlD3Z8xtRC7rAdanFB_NRtoKpiKh2y3H1IU0Dx_DSMw5tOkdhhc_s8_pXAOsfWjzW2442QWQBy6rDaXcCOWU_z80BYqO5Mp8MdmLA\n\n",

    // siteUrl: "https://genre.sharepoint.com/sites/G2Applications-DEV/FormsLibrary",
    siteUrl: "https://genstargenesis.sharepoint.com/sites/Indexing-dev",

    // listName: "Documents",
    listName: "G2IndexingUnderwriting",

    documentSetName: "MubashirTest",
    // Upload now derives the authenticated user from token claims.

    columns: {
      "Title": "",
      "ContentType": "",
      "CreatedBy": ""
    },

    showActions: true,
    showBreadcrumb: true,
    showUploadControls: true
  }
}

